# Generated by Django 3.0 on 2019-12-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('postpic', models.ImageField(blank=True, null=True, upload_to='')),
                ('external_link', models.TextField(blank=True, verbose_name='link')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
