# Generated by Django 3.0 on 2019-12-18 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191218_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_follow',
            field=models.ManyToManyField(blank=True, related_name='ifollow', to=settings.AUTH_USER_MODEL),
        ),
    ]
