# Generated by Django 3.0 on 2019-12-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accptedfriend', to=settings.AUTH_USER_MODEL, verbose_name='friend'),
        ),
    ]
