# Generated by Django 3.0 on 2019-12-19 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191219_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='isfriend', to=settings.AUTH_USER_MODEL, verbose_name='friend'),
        ),
    ]
